# fly.toml app configuration file generated for maple-electric-dev on 2024-11-14T16:31:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maple-electric-dev'
primary_region = 'ams'

[build]
image = 'electricsql/electric:0.9.3'

[env]
DATABASE_URL = 'postgresql://postgres:5FduiVxNbt5Ye8Qi@db.hxwmftwwlibnzjzeqhgv.supabase.co:5432/postgres'
ELECTRIC_DATABASE_USE_IPV6 = 'true'

[http_service]
internal_port = 3000
force_https = true

[[http_service.checks]]
interval = '10s'
timeout = '2s'
grace_period = '20s'
method = 'GET'
path = '/v1/health'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
