// Generated by Wrangler by running `wrangler types`

interface Env {
	LOG_LEVEL: "INFO"
	API_BASE_URL: "https://api.maple.dev"
	APP_BASE_URL: "https://app.maple.dev"
	HYPERDRIVE: Hyperdrive
	SYNC_TRANSACTIONS_WORKFLOW: Workflow
}
