// Generated by Wrangler by running `wrangler types`

interface Env {
	DATABASE_URL: string;
	PLAID_CLIENT_ID: string;
	PLAID_SECRET: string;
	PLAID_ENV: string;
	LOG_LEVEL: string;
	GO_CARDLESS_SECRET_ID: string;
	GO_CARDLESS_SECRET_KEY: string;
	SYNC_ACCOUNT_WORKFLOW: Workflow;
}
