// Generated by Wrangler by running `wrangler types`

interface Env {
	API_BASE_URL: "http://localhost:8787";
	APP_BASE_URL: "http://localhost:3000";
	DATABASE_URL: string;
	LOG_LEVEL: string;
	GO_CARDLESS_SECRET_ID: string;
	GO_CARDLESS_SECRET_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_PUBLISHABLE_KEY: string;
}
